# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

ENV['RCT_USE_RN_DEP'] = '0'
ENV['RCT_USE_PREBUILT_RNCORE'] = '0'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'NiCardManagementExample' do
  config = use_native_modules!

  # Workaround for missing Folly headers in some RN/Folly resolution cases.
  pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'NiCardManagementExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => true
    )

    # Some RCT-Folly releases ship Expected.h with coroutine support enabled,
    # but without the corresponding folly/coro/Coroutine.h header.
    # Patch the guard only in that mismatch case to keep builds unblocked.
    coroutine_h = File.join(installer.sandbox.root.to_s, 'RCT-Folly', 'folly', 'coro', 'Coroutine.h')
    folly_headers = %w[Expected.h Optional.h]
    if !File.exist?(coroutine_h)
      folly_headers.each do |header_name|
        header_path = File.join(installer.sandbox.root.to_s, 'RCT-Folly', 'folly', header_name)
        next unless File.exist?(header_path)

        begin
          unless File.writable?(header_path)
            require 'fileutils'
            FileUtils.chmod(0644, header_path)
          end
          content = File.read(header_path)
          patched = content.sub(
            '#if FOLLY_HAS_COROUTINES',
            '#if 0 // Disabled because RCT-Folly package misses folly/coro/Coroutine.h'
          )
          File.write(header_path, patched) if patched != content
        rescue => e
          Pod::UI.warn("Skipping RCT-Folly #{header_name} patch: #{e.message}")
        end
      end
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= ['$(inherited)']
        build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-DFOLLY_CFG_NO_COROUTINES=1'
        build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-DFOLLY_HAS_COROUTINES=0'
      end
    end

    if respond_to?(:__apply_Xcode_12_5_M1_post_install_workaround, true)
      __apply_Xcode_12_5_M1_post_install_workaround(installer)
    end
  end
end
